/* GENERATED by scripts/build-chart-data.mjs from campaigns-2025.csv.
 * ⛔ Do not edit: every point is read from the file, deduplicated, so a chart cannot
 * carry a number that is not in the data. Regenerate after any dataset change. */

export type ChartSpec = {
  title: string;
  series: { name: string; points: [string, number][] }[];
  bands?: { from: string; to: string; label: string }[];
};

export const CHARTS: Record<string, ChartSpec> = {
  "march": {
    "title": "Quotes started per week, Jan to Jun",
    "series": [
      {
        "name": "brand-search",
        "points": [
          [
            "2025-01-06",
            122
          ],
          [
            "2025-01-13",
            114
          ],
          [
            "2025-01-20",
            111
          ],
          [
            "2025-01-27",
            114
          ],
          [
            "2025-02-03",
            134
          ],
          [
            "2025-02-10",
            147
          ],
          [
            "2025-02-17",
            135
          ],
          [
            "2025-02-24",
            137
          ],
          [
            "2025-03-03",
            138
          ],
          [
            "2025-03-10",
            297
          ],
          [
            "2025-03-17",
            310
          ],
          [
            "2025-03-24",
            259
          ],
          [
            "2025-03-31",
            217
          ],
          [
            "2025-04-07",
            124
          ],
          [
            "2025-04-14",
            124
          ],
          [
            "2025-04-21",
            116
          ],
          [
            "2025-04-28",
            118
          ],
          [
            "2025-05-05",
            115
          ],
          [
            "2025-05-12",
            114
          ],
          [
            "2025-05-19",
            125
          ],
          [
            "2025-05-26",
            115
          ],
          [
            "2025-06-02",
            111
          ],
          [
            "2025-06-09",
            112
          ],
          [
            "2025-06-16",
            122
          ],
          [
            "2025-06-23",
            118
          ],
          [
            "2025-06-30",
            125
          ]
        ]
      },
      {
        "name": "price-comparison",
        "points": [
          [
            "2025-01-06",
            62
          ],
          [
            "2025-01-13",
            60
          ],
          [
            "2025-01-20",
            64
          ],
          [
            "2025-01-27",
            63
          ],
          [
            "2025-02-03",
            62
          ],
          [
            "2025-02-10",
            63
          ],
          [
            "2025-02-17",
            62
          ],
          [
            "2025-02-24",
            61
          ],
          [
            "2025-03-03",
            62
          ],
          [
            "2025-03-10",
            134
          ],
          [
            "2025-03-17",
            144
          ],
          [
            "2025-03-24",
            116
          ],
          [
            "2025-03-31",
            95
          ],
          [
            "2025-04-07",
            69
          ],
          [
            "2025-04-14",
            67
          ],
          [
            "2025-04-21",
            68
          ],
          [
            "2025-04-28",
            68
          ],
          [
            "2025-05-05",
            64
          ],
          [
            "2025-05-12",
            68
          ],
          [
            "2025-05-19",
            68
          ],
          [
            "2025-05-26",
            66
          ],
          [
            "2025-06-02",
            60
          ],
          [
            "2025-06-09",
            59
          ],
          [
            "2025-06-16",
            60
          ],
          [
            "2025-06-23",
            65
          ],
          [
            "2025-06-30",
            60
          ]
        ]
      }
    ],
    "bands": [
      {
        "from": "2025-03-10",
        "to": "2025-03-31",
        "label": "Ardline letter"
      }
    ]
  },
  "radio-halo": {
    "title": "brand-search quotes per week, full year",
    "series": [
      {
        "name": "brand-search",
        "points": [
          [
            "2025-01-06",
            122
          ],
          [
            "2025-01-13",
            114
          ],
          [
            "2025-01-20",
            111
          ],
          [
            "2025-01-27",
            114
          ],
          [
            "2025-02-03",
            134
          ],
          [
            "2025-02-10",
            147
          ],
          [
            "2025-02-17",
            135
          ],
          [
            "2025-02-24",
            137
          ],
          [
            "2025-03-03",
            138
          ],
          [
            "2025-03-10",
            297
          ],
          [
            "2025-03-17",
            310
          ],
          [
            "2025-03-24",
            259
          ],
          [
            "2025-03-31",
            217
          ],
          [
            "2025-04-07",
            124
          ],
          [
            "2025-04-14",
            124
          ],
          [
            "2025-04-21",
            116
          ],
          [
            "2025-04-28",
            118
          ],
          [
            "2025-05-05",
            115
          ],
          [
            "2025-05-12",
            114
          ],
          [
            "2025-05-19",
            125
          ],
          [
            "2025-05-26",
            115
          ],
          [
            "2025-06-02",
            111
          ],
          [
            "2025-06-09",
            112
          ],
          [
            "2025-06-16",
            122
          ],
          [
            "2025-06-23",
            118
          ],
          [
            "2025-06-30",
            125
          ],
          [
            "2025-07-07",
            121
          ],
          [
            "2025-07-14",
            120
          ],
          [
            "2025-07-21",
            115
          ],
          [
            "2025-07-28",
            112
          ],
          [
            "2025-08-04",
            123
          ],
          [
            "2025-08-11",
            112
          ],
          [
            "2025-08-18",
            116
          ],
          [
            "2025-08-25",
            114
          ],
          [
            "2025-09-01",
            145
          ],
          [
            "2025-09-08",
            148
          ],
          [
            "2025-09-15",
            135
          ],
          [
            "2025-09-22",
            146
          ],
          [
            "2025-09-29",
            144
          ],
          [
            "2025-10-06",
            147
          ],
          [
            "2025-10-13",
            146
          ],
          [
            "2025-10-20",
            133
          ],
          [
            "2025-10-27",
            147
          ],
          [
            "2025-11-03",
            123
          ],
          [
            "2025-11-10",
            115
          ],
          [
            "2025-11-17",
            115
          ],
          [
            "2025-11-24",
            122
          ],
          [
            "2025-12-01",
            113
          ],
          [
            "2025-12-08",
            122
          ],
          [
            "2025-12-15",
            122
          ],
          [
            "2025-12-22",
            112
          ],
          [
            "2025-12-29",
            120
          ]
        ]
      }
    ],
    "bands": [
      {
        "from": "2025-02-03",
        "to": "2025-03-31",
        "label": "radio burst 1"
      },
      {
        "from": "2025-09-01",
        "to": "2025-10-27",
        "label": "radio burst 2"
      }
    ]
  },
  "home-worker-profile": {
    "title": "Share of group on each measure, %",
    "series": [
      {
        "name": "works from home",
        "points": [
          [
            "25-44",
            62
          ],
          [
            "apartment",
            6
          ],
          [
            "Dublin",
            22
          ],
          [
            "auto-renew",
            44
          ],
          [
            "switched in 3y",
            62
          ],
          [
            "3+ quotes",
            37
          ],
          [
            "2+ policies",
            37
          ],
          [
            "claim-free",
            81
          ]
        ]
      },
      {
        "name": "everyone else",
        "points": [
          [
            "25-44",
            39
          ],
          [
            "apartment",
            18
          ],
          [
            "Dublin",
            36
          ],
          [
            "auto-renew",
            44
          ],
          [
            "switched in 3y",
            62
          ],
          [
            "3+ quotes",
            38
          ],
          [
            "2+ policies",
            39
          ],
          [
            "claim-free",
            82
          ]
        ]
      }
    ]
  },
  "segment-behaviour": {
    "title": "Share of segment on each behaviour, %",
    "series": [
      {
        "name": "Payer",
        "points": [
          [
            "auto-renew",
            90
          ],
          [
            "switched in 3y",
            8
          ],
          [
            "3+ quotes",
            0
          ],
          [
            "2+ policies",
            16
          ],
          [
            "acted in 7 days",
            9
          ]
        ]
      },
      {
        "name": "Switcher",
        "points": [
          [
            "auto-renew",
            9
          ],
          [
            "switched in 3y",
            100
          ],
          [
            "3+ quotes",
            89
          ],
          [
            "2+ policies",
            9
          ],
          [
            "acted in 7 days",
            96
          ]
        ]
      },
      {
        "name": "Juggler",
        "points": [
          [
            "auto-renew",
            42
          ],
          [
            "switched in 3y",
            71
          ],
          [
            "3+ quotes",
            11
          ],
          [
            "2+ policies",
            100
          ],
          [
            "acted in 7 days",
            33
          ]
        ]
      }
    ]
  }
};

export type YardstickSpec = {
  title: string;
  line: number;
  lineLabel: string;
  pairs: { name: string; value: number; subject?: boolean }[];
};

export const YARDSTICK: YardstickSpec = {
  "title": "How similar are the two groups, %",
  "line": 90,
  "lineLabel": "the same people",
  "pairs": [
    {
      "name": "Payer vs Switcher",
      "value": 60.8
    },
    {
      "name": "Payer vs Juggler",
      "value": 64.9
    },
    {
      "name": "Switcher vs Juggler",
      "value": 62.9
    },
    {
      "name": "home workers vs everyone else",
      "value": 92.1,
      "subject": true
    }
  ]
};
