/* ⛔ GENERATED by scripts/build-context-sessions.mjs from the saved replies in
   course-files/module-1/context/. Do not edit: re-run the script. */
import type { Turn } from "./writerSession";

export const CONTEXT_WITHOUT_SESSION: Turn[] = [
  {
    "who": "you",
    "text": "Summarise our campaign results."
  },
  {
    "who": "writer",
    "blocks": [
      {
        "kind": "md",
        "text": "**2025 campaign summary**"
      },
      {
        "kind": "md",
        "text": "**Full year, 52 weeks (5 channels):** €308,047 spend → 16,820 quotes started → 5,468 new policies. Blended **CPA €56**, quote→policy conversion **32.5%**."
      },
      {
        "kind": "table",
        "head": [
          "Channel",
          "Spend",
          "% spend",
          "Policies",
          "% policies",
          "CPQ",
          "**CPA**",
          "Quote→policy"
        ],
        "align": [
          "l",
          "l",
          "l",
          "l",
          "l",
          "l",
          "l",
          "l"
        ],
        "rows": [
          [
            "price-comparison (switcher)",
            "€19,917",
            "6%",
            "2,028",
            "37%",
            "€5.71",
            "**€9.82**",
            "58.1%"
          ],
          [
            "brand-search (all)",
            "€72,775",
            "24%",
            "2,127",
            "39%",
            "€10.31",
            "**€34.21**",
            "30.1%"
          ],
          [
            "podcast (juggler)",
            "€36,494",
            "12%",
            "398",
            "7%",
            "€28.36",
            "**€91.69**",
            "30.9%"
          ],
          [
            "social (juggler)",
            "€96,320",
            "31%",
            "784",
            "14%",
            "€20.99",
            "**€122.86**",
            "17.1%"
          ],
          [
            "radio (payer), 18 wks",
            "€82,541",
            "27%",
            "131",
            "2%",
            "€210.03",
            "**€630.08**",
            "33.3%"
          ]
        ]
      },
      {
        "kind": "md",
        "text": "**What stands out**"
      },
      {
        "kind": "md",
        "text": "**1. Spend and results are close to inverted.** Social and radio together took 58% of budget and returned 17% of policies. Price-comparison took 6% of budget and returned 37%. Quarterly CPA was stable (€47–61), so this is a structural allocation issue, not a bad patch."
      },
      {
        "kind": "md",
        "text": "**2. Social's problem is conversion, not traffic.** It generates the second-highest quote volume at a respectable €21 CPQ, but only 17.1% of those quotes convert vs 30–58% everywhere else — dead steady all 52 weeks. If social quotes converted at even the 30% others manage, its CPA would fall from €123 to ~€70. Worth investigating whether it's landing-page/quote-flow fit or audience quality before cutting."
      },
      {
        "kind": "md",
        "text": "**3. Radio looks poor even when you credit it generously.** During the two flights (Feb–Mar, Sep–Oct), brand-search quotes ran ~20% above dark weeks at identical spend — a plausible awareness halo. Crediting radio with all of that lift (~101 extra policies) still only brings its CPA from €630 to ~€356, more than double the next-worst channel. Price-comparison and social showed no flight-week lift at all."
      },
      {
        "kind": "md",
        "text": "**4. Price-comparison hit a ceiling in April–May.** Spend was raised from ~€350 to ~€560/week for 8 weeks. Quotes rose only 10% (61→67/wk): **+€1,656 spend bought ~24 extra policies, an incremental CPA of ~€68** against a €10 baseline. The channel is the most efficient you have, but it does not scale linearly — worth retesting with a smaller step-up before assuming headroom."
      },
      {
        "kind": "md",
        "text": "**Data caveats — read before quoting these figures**"
      },
      {
        "kind": "list",
        "ordered": false,
        "items": [
          "**An unexplained demand spike, 10–31 March**, drove brand-search quotes +130% and price-comparison +95% with **no change in spend**, then decayed back to baseline. That's roughly **322 policies, ~6% of the year's total, from four weeks nobody paid for.** It sits inside the first radio flight, but the second flight produced nothing like it, so I'd treat it as an external event (competitor exit, PR, pricing change, or an attribution/tracking change) rather than media-driven. Worth confirming with whoever was in-market then — if it's excluded, brand-search CPA rises from €34 to ~€40.",
          "**Podcast tracking outage, 16–30 June:** three consecutive weeks show normal spend (~€700/wk) but exactly zero quotes and zero policies, bracketed by ~26 quotes/week either side. Almost certainly broken tracking, not a real collapse. It costs podcast ~24 policies and overstates its CPA by ~7%.",
          "**One exact duplicate row** (2025-07-14, social/juggler) — I removed it; 226 unique rows analysed. No missing values, no other gaps, all 52 weeks present."
        ]
      },
      {
        "kind": "md",
        "text": "**Suggested next steps**"
      },
      {
        "kind": "list",
        "ordered": true,
        "items": [
          "Confirm what happened in March before it gets baked into 2026 baselines.",
          "Fix podcast tracking and restate June.",
          "Diagnose the social quote→policy gap — it's the single largest recoverable sum in the plan (~€50k of spend sitting behind a 17% conversion rate).",
          "Decide on radio deliberately: it needs a brand/awareness justification, because the acquisition maths doesn't support €82k at €630 CPA."
        ]
      }
    ]
  }
];

export const CONTEXT_WITH_SESSION: Turn[] = [
  {
    "who": "you",
    "text": "Task: write a one-page summary of the campaign results in the attached file.\nBackground: it is for the quarterly review, and we are being asked whether to keep spending.\nAudience: the CFO. She cares about what we got for the money, not impressions.\nFormat: one page. A short table of numbers, then three lines of plain English.\nBar: she should be able to decide in two minutes without coming back to me."
  },
  {
    "who": "writer",
    "blocks": [
      {
        "kind": "md",
        "text": "Analysed all 227 rows (52 weeks, 5 channels). One issue worth knowing up front: the file has an exact duplicate row (social, week of 14 Jul). Everything below excludes it."
      },
      {
        "kind": "md",
        "text": "**2025 Campaign Results — Quarterly Review**"
      },
      {
        "kind": "md",
        "text": "**Question on the table: keep spending?**"
      },
      {
        "kind": "table",
        "head": [
          "Channel",
          "Spend",
          "% of spend",
          "New policies",
          "% of policies",
          "Cost per policy",
          "Quote → policy"
        ],
        "align": [
          "l",
          "l",
          "l",
          "l",
          "l",
          "l",
          "l"
        ],
        "rows": [
          [
            "Price comparison",
            "€19,917",
            "6%",
            "2,028",
            "37%",
            "**€10**",
            "58%"
          ],
          [
            "Brand search",
            "€72,775",
            "24%",
            "2,127",
            "39%",
            "**€34**",
            "30%"
          ],
          [
            "Podcast",
            "€36,494",
            "12%",
            "398",
            "7%",
            "€92",
            "31%"
          ],
          [
            "Social",
            "€96,320",
            "31%",
            "784",
            "14%",
            "**€123**",
            "17%"
          ],
          [
            "Radio",
            "€82,541",
            "27%",
            "131",
            "2%",
            "**€630** (€316 adj.)",
            "33%"
          ],
          [
            "**Total**",
            "**€308,047**",
            "100%",
            "**5,468**",
            "100%",
            "**€56**",
            "33%"
          ]
        ]
      },
      {
        "kind": "md",
        "text": "**Yes, keep spending — but not this mix.** €308k bought 5,468 policies at €56 blended. The problem is concentration: social and radio took 58% of the budget and delivered 17% of the policies, while price comparison delivered 37% of policies on 6% of spend."
      },
      {
        "kind": "md",
        "text": "**Don't assume we can just move the money to the cheap channels.** We accidentally ran that test: in Apr–May we raised price-comparison spend 60% (€351 → €559/week) and got only 3.4 extra policies a week — the incremental ones cost €62, not €10. Those channels are capped by how many people are already shopping, not by budget."
      },
      {
        "kind": "md",
        "text": "**So the cut is social, not radio.** Radio looks worst at €630, but brand search produces 43 policies in every single radio week versus 35 in every non-radio week (+7/week, zero overlap across two flights) — crediting that halo puts radio at ~€316, and it's the only lever that lifts our cheapest channel. Social has run all 52 weeks with no gap, so its €96k has never been tested at all. Recommend a 6-week dark test on social in Q1 and reallocating if policies hold."
      },
      {
        "kind": "md",
        "text": "Two things to discount before you compare this to plan:"
      },
      {
        "kind": "list",
        "ordered": false,
        "items": [
          "**Weeks of 10–31 Mar were free.** Brand-search and price-comparison policies roughly doubled on flat spend — about 324 policies (6% of the year) were demand, not marketing. Excluding them, true blended cost per policy is **€60**, not €56.",
          "**Radio's adjusted €316 is an estimate**, based on the brand-search lift above. Its directly attributed cost stands at €630."
        ]
      }
    ]
  }
];
