/* Generated by decks/publish_zorro.py in the gym repo on 12 Sep 2026 from the build guide, the student pages, the runbook,
   the runner and the messaging pack: ~/projects/clients/ucd/ie-week-gym-agent. Do not edit here; edit the pages and rerun it. */

export const ZORRO_KNOWLEDGE = `### The build guide, step by step (decks/the-build-guide.md)

# The build guide, as plain text (for Isa). One step at a time.

## A. Get set up. About twenty minutes, once.

### Step 1. Download the gym folder
Go to runwithfoxes.com/zorro, type the password, scroll to "The gym files" and click Download beside gimnasio-zorro.zip. It lands in your Downloads folder.
On screen: runwithfoxes.com/zorro gimnasio-zorro.zip The whole folder: the three data files, the three pages, the four role pages, the runbook, the set-up sheet, and the runner and the clock in tools. Download
You should see: A file called gimnasio-zorro.zip in Downloads.


### Step 2. Unzip it and put the folder on your Desktop
Open Downloads. Double-click gimnasio-zorro.zip. A folder called gimnasio-zorro appears beside it. Drag that folder onto your Desktop.
On screen: Desktop gimnasio-zorro/ data/ members.csv checkins.csv email_log.csv messaging/ gimnasio-zorro.md email-voice-and-rules.md messages-by-goal.md pages/ carlos-role.md enrique-role.md cato-brief.md ... tools/ attio.py
You should see: A folder called gimnasio-zorro on your Desktop with four folders inside it: data, messaging, pages, tools.
On a Mac  double-clicking the zip unzips it.  On Windows  right-click the zip and choose Extract All, then Extract.

### Step 3. Open a terminal
A terminal is a window where you type commands instead of clicking. Claude Code runs inside it.
On screen: terminal Last login: Mon Sep 14 18:02:11 $
You should see: A mostly empty window with a line ending in a dollar sign or a greater-than sign, and a blinking cursor. That is where you type.
On a Mac  press Cmd and Space together, type Terminal, press Enter.  On Windows  press the Windows key, type PowerShell, press Enter.

### Step 4. Go into the gym folder
Type the line below exactly, then press Enter. Nothing dramatic happens. The prompt now shows the folder name, which means you are inside it.
On screen: terminal $ cd Desktop/gimnasio-zorro gimnasio-zorro $
You should see: The prompt changes to include gimnasio-zorro.
On a Mac  cd Desktop/gimnasio-zorro  On Windows  cd Desktop\\gimnasio-zorro

### Step 5. Check you are in the right place
Type ls and press Enter. It lists what is in the folder.
On screen: terminal gimnasio-zorro $ ls data messaging pages tools
You should see: Four names: data, messaging, pages, tools. If you see something else, you are in the wrong folder. Type cd and press Enter to go home, then do the step above again.
On a Mac  ls  On Windows  dir

### Step 6. Start Claude Code
Type claude and press Enter. The first time, it opens your browser to log in. Log in with your Claude account and come back to the terminal. It may ask "Do you trust the files in this folder?" Press Enter for yes.
On screen: terminal gimnasio-zorro $ claude Welcome to Claude Code Do you trust the files in this folder? Yes &gt;
You should see: A box with a > prompt. Everything from here on, you type into that box and press Enter.


### Step 7. Know the one thing it will ask you
Claude Code asks before it reads or writes a file, and before it runs a command. When it asks, read what it wants to do, then press Enter to say yes. You will do this a lot. It is not an error.
On screen: claude code Claude wants to create carlos.md Yes Yes, and don't ask again for this folder No press Enter
You should see: The thing it asked for gets done, and it tells you.


## B. Make Carlos, the one who counts. Tuesday morning.

### Step 8. Make the page
Carlos is a text file called carlos.md with four headings on it. Ask Claude Code to make the empty file. Type the line below into the > box and press Enter.
On screen: claude code &gt; Make a file called carlos.md in this folder with these four headings and nothing under them: What it produces. Where it lands. How it knows it is done. What it does not do. Created carlos.md with the four headings.
You should see: A new file called carlos.md in the gym folder. Open the folder on your Desktop and you will see it.


### Step 9. Answer the first question: what it produces
Now you write the job. Tell Claude Code what to put under the first heading. This is what a good answer looks like. Put it in your own words, but keep every number in it.
On screen: carlos.md ## What it produces One row per member, with these fields: member_id, first_name, last_name, goal, notes, visits_per_week_last12 (twelve whole numbers, oldest week first), usual_per_week (the average of the first nine of those twelve weeks, to two decimal places), visits_last3 (the last three weeks added up). A week runs Monday to Sunday. The twelve weeks are the twelve full weeks before the Monday being run. Only swipes dated before that Monday count.
You should see: Type: "Put this under What it produces:" and then your answer, and press Enter. Claude Code writes it into the file and says so.


### Step 10. Answer the other three
Do the same for the other three headings. These are good answers. Notice each one can be checked, and the last one is a list of things it must not do.
On screen: carlos.md ## Where it lands A file called carlos-out.json in this folder, one row per member. And one line printed to say how many rows were written. ## How it knows it is done Every member in data/members.csv has a row. Running it twice on the same Monday gives the same file. ## What it does not do It does not decide who is slipping. It does not write to any member. It does not touch Attio.
You should see: carlos.md with all four questions answered. Ask Claude Code "show me carlos.md" to read it back.


### Step 11. Run it for one member
This is what "run it" means: you tell Claude Code to read the page and do what it says, for one member. Type the line below and press Enter. It will read the files, count the swipes, and may write a small program to do the counting. That is fine. That program is Carlos. It takes about a minute.
On screen: claude code &gt; Read carlos.md and do what it says, but for member Z0811 only, as of Monday 31 August 2026. Use the files in data. Show me the row you produce. Here is the row for Sergio Rubio (Z0811), as of Monday 31 August 2026: {"member_id": "Z0811", "first_name": "Sergio", "last_name": "Rubio", "goal": "build muscle", "notes": "", "visits_per_week_last12": [2, 4, 3, 3, 3, 3, 4, 3, 3, 0, 0, 0], "usual_per_week": 3.11, "visits_last3": 0} He came in about three times a week through the first nine weeks: 28 visits, so 28 divided by 9 is 3.11. His last swipe before the cut-off was Saturday 8 August, so the last three weeks add up to 0.
You should see: One row for Sergio Rubio. The twelve numbers should be 2 4 3 3 3 3 4 3 3 0 0 0, the usual should be 3.11, and the last three weeks should be 0. If your numbers are different, your page said something different. Read it again.


### Step 12. Check the row against the sheet
Do not take its word for it. Open the check-ins sheet on the zorro page, use the filter to show only Z0811, and count his swipes in the last three weeks before 31 August. There should be none. Then count one of the earlier weeks and compare it to the row.
On screen: Gimnasio Zorro, the check-ins member id swiped in at Z0811 2026-08-03 18:41 Z0811 2026-08-05 18:22 Z0811 2026-08-08 10:15 (nothing between 10 August and 30 August)
You should see: The numbers in the row match what you counted. If they do not, tell Claude Code exactly which number is wrong and what you counted. It will find why.


### Step 13. Run it for your team's ten
Download your team's ten-member pack from the zorro page and drag it into the gym folder. Then type the line below. Change team01 to your team number.
On screen: claude code &gt; Read carlos.md and do what it says for every member listed in team01-build10.csv, as of Monday 31 August 2026. Show me the ten rows. Ten rows follow. {"member_id": "Z0652", "first_name": "Alba", ... "visits_last3": 1} {"member_id": "Z0867", ...} ...
You should see: Ten rows. Look at each one against the visits in the pack file. Where a row is wrong, fix the wording in carlos.md, then run the ten again.


### Step 14. Run it for all 900
Now the real thing. Type the line below and press Enter. It takes a few minutes. It will ask before it writes the file. Press Enter for yes.
On screen: claude code &gt; Read carlos.md and do what it says for every member in data/members.csv, as of Monday 31 August 2026. Write the file carlos.md says to write. Wrote carlos-out.json with 900 rows.
You should see: A file called carlos-out.json in the gym folder, and a line saying 900 rows. Ask "how many rows are in carlos-out.json?" and it must say 900.


### Step 15. Run it a second time
This is the test that matters. Type the same line again, exactly. It should give exactly the same file. Then ask it to compare.
On screen: claude code &gt; Read carlos.md and do what it says for every member in data/members.csv, as of Monday 31 August 2026. Write the file carlos.md says to write. Wrote carlos-out.json with 900 rows. &gt; Compare the file you just wrote with the one you wrote before. Are they identical, row for row? Yes. All 900 rows are identical.
You should see: Yes, identical. If it says no, the page is not finished: something in carlos.md leaves room for a different answer. Ask Claude Code which rows differ and why, and tighten the page.


### Step 16. Stuck?
Ask Isa on the zorro page first. Tell her the step number, what you typed, and what you saw. She has read every page. If she cannot help, ask Julie or Paul in the room.




## C. Make Enrique, the one who writes and sends. Tuesday.

### Step 17. Make the page
Same as Carlos. Ask Claude Code to make enrique.md with the four headings. Then answer them. Enrique reads Carlos's file and the three pages in messaging. He never opens the check-ins.
On screen: enrique.md ## What it produces One decision per row of carlos-out.json: member_id, decision (draft, skip or ask), reason (one line quoting the numbers or the note), email (the email, or nothing). ## Where it lands A file called enrique-out.json in this folder. For every draft, the email goes in data/email_log.csv with the date. Later: the reason and the email on the member's card in Attio. ## What it does not do It never opens data/checkins.csv. It does no arithmetic. It never writes to a member whose note says away or injured. It never mentions fees, renewal, or the member's private life.
You should see: enrique.md with the four answers. The rules for the email are in messaging/email-voice-and-rules.md; tell Claude Code to read that page and messages-by-goal.md when it decides.


### Step 18. Run it for one member
Type the line below. It reads the row Carlos made, the three pages, and decides.
On screen: claude code &gt; Read enrique.md, the three pages in messaging, and carlos-out.json. Do what enrique.md says for member Z0811 only. Show me the decision, the reason and the email. Decision: draft. Reason: visits_last3 0 against usual_per_week 3.11; no note. Hi Sergio, Marta here, and I noticed you have not been in for a few weeks. You put real work into what you built here, and it is worth keeping. The floor has been quiet in the evenings and your bench is free. Could you come in for one session this week? Marta
You should see: A decision, a reason with the numbers in it, and an email under eighty words with one ask and nothing about fees or his private life. Read it as Marta. Would she send it?


### Step 19. Then ten, then all 900, then a second time
Exactly as for Carlos: your team's ten, then every row in carlos-out.json, then the same line again and "are they identical?". The decisions must not change between runs.

You should see: enrique-out.json with 900 rows, the same twice.


## D. Connect Attio, so the emails land on the cards.

### Step 20. Make the workspace
One person on the team goes to attio.com and makes a free workspace. Name it Zorro and your team number. Invite the others by email. Do not pay for anything.

You should see: Everyone on the team can open the workspace and sees an empty People list.


### Step 21. Make a token
In Attio, open Settings, then Developers, then make a new access token. Give it read and write access to People and to object configuration. Copy the token. It is one long line of letters and numbers. You only see it once.
On screen: attio, settings, developers Access tokens New access token Name: zorro Scopes: People read and write, Object configuration read and write Copy
You should see: A long token on your clipboard.


### Step 22. Put the token in a file called .env
Back in Claude Code, type the line below, pasting your token in place of the dots. Claude Code makes the file. Never paste the token anywhere else, and never put it in a page.
On screen: claude code &gt; Make a file called .env in this folder with exactly one line: ATTIO_TOKEN=.......... Created .env. I will not print the token back.
You should see: A file called .env in the gym folder. You will not see it in the Desktop folder, because files that start with a dot are hidden. That is fine.


### Step 23. Load the members
The loader is in tools. Ask Claude Code to run it, three times, in this order. The first makes the fields on People, the second puts the 900 members in, the third counts them.
On screen: claude code &gt; Run python3 tools/attio.py setup, then python3 tools/attio.py import, then python3 tools/attio.py count. Show me what each prints. made member_id ... made status ... option steady ... imported 900 members 900 people in the workspace
You should see: Open Attio. People now has 900 cards, each with a goal, a plan and a status of steady.


### Step 24. Send Enrique's emails to the cards
Now Enrique's decisions go onto the cards. Ask Claude Code to write each draft as emailed, with the reason and the email, and each ask as ask marta.
On screen: claude code &gt; For every row in enrique-out.json, put the reason and the email on that member's card in Attio and set the status: emailed for a draft, ask marta for an ask. Use tools/attio.py as the example of how to write to a card. Written 65 cards as emailed and 10 as ask marta.
You should see: In Attio, the emailed members carry the reason and the email on their card. Click Sergio Rubio.


## E. Make Cato, the one who checks. Thursday.

### Step 25. Make the page and run him
cato.md is the same four questions. His job is to assume Carlos and Enrique are wrong and prove it: recount the numbers from the check-ins himself, decide for each member from enrique.md's rules himself, and write disagree wherever his answer differs. His page is in pages/cato-brief.md. Under Where it lands, name a file: cato-out.json in this folder, one row per member with his verdict, agree or disagree, and why. The runner in Part G looks for that file.
On screen: claude code &gt; Read cato.md and pages/cato-brief.md. Do what they say for every member, as of Monday 31 August 2026, without reading carlos-out.json or enrique-out.json until you have your own answer. Then compare, write the file cato.md says to write, and show me every row where you disagree and why. 900 rows checked. 3 disagreements: Z0693 Lucía Rodríguez: Enrique said draft. Her note says she comes every other week. Skip.
You should see: A list of rows where Cato disagrees, each with the reason quoted from the data. Every one of those is a line to fix in carlos.md or enrique.md. Fix it, run again, and the list should get shorter.


## F. Make Rosa, the one who counts who came back. Tuesday, after Enrique.

### Step 26. Make the page
Same four headings, in a file called rosa.md. Her page is in pages/rosa-role.md; put it in your own words but keep the fields. Rosa runs two weeks after Enrique. She reads who was written to on a Monday and the check-ins for the fourteen days after, and counts who came back.
On screen: rosa.md ## What it produces One row per member Enrique wrote to on the Monday named: member_id, name, visits_after (their swipes in the fourteen days from that Monday), returned (true if visits_after is more than 0). Above the rows: sent_on, checked_on, written_to, came_back, and one line for Marta: "On 31 August we wrote to 65 members. 28 of them have been back in the two weeks since." ## Where it lands A file called rosa-out.json in this folder. Later: each of those cards in Attio moves from emailed to came back or didn't come back. ## What it does not do It does not write to any member. It does not decide who to write to next. A reply from someone who has not been back goes to Marta word for word, not to the agent.
You should see: rosa.md with the four answers.


### Step 27. Run her for the 31 August emails
Type the line below. She reads enrique-out.json for who was written to on 31 August, and the check-ins from 31 August to 13 September.
On screen: claude code &gt; Read rosa.md. Do what it says for the emails sent on Monday 31 August 2026, reading the check-ins for the fourteen days from that Monday. Write the file rosa.md says to write, and show me Marta's line. Wrote rosa-out.json with 65 rows. On 31 August we wrote to 65 members. 28 of them have been back in the two weeks since, 43%.
You should see: Marta's line, with 28 of 65. If your Enrique wrote to a different number of members, your numbers will differ, and that is fine. What must hold: came_back plus the members who did not return equals written_to, and running it twice gives the same file.


## G. Give them a clock, so nobody has to type anything on a Monday. Tuesday.

### Step 28. Run the runner by hand, once
The runner is tools/monday.py. It runs your four pages in order and stops the moment one of them has not written its file. Run it yourself first, for one member, so you can see what it does before a clock does it for you.
On screen: terminal python3 tools/monday.py --member Z0811 --force --monday 2026-08-31 2026-09-12 10:17:01 monday=2026-08-31 start (member Z0811) 2026-09-12 10:20:18 monday=2026-08-31 carlos ok: carlos-out.json written 2026-09-12 10:20:18 monday=2026-08-31 enrique skipped: no enrique.md in the folder yet 2026-09-12 10:20:18 monday=2026-08-31 cato skipped: no cato.md in the folder yet 2026-09-12 10:20:18 monday=2026-08-31 rosa skipped: no rosa.md in the folder yet 2026-09-12 10:20:18 monday=2026-08-31 done
You should see: Those lines, and the same lines in a new file called heartbeat.log in the gym folder. That file is the proof a run happened. An agent you have not built yet is skipped, not failed. The lines above are from a real run on a clean copy of the folder with only carlos.md in it; Carlos took about three minutes for one member.
On a Mac  the line above, in Terminal, from inside the gym folder.  On Windows  the same line with python instead of python3, in PowerShell, from inside the gym folder.

### Step 29. Set a two-minute clock and watch it fire
Now let a clock start it. Type the line for your machine and then do nothing for two minutes. Do not touch the keyboard. Watch the folder.
On screen: terminal zsh tools/schedule.sh demo the clock is set: every 120 seconds it wakes tools/monday.py --member Z0811 proof of a run is heartbeat.log in the gym folder, not this line
You should see: After two minutes, heartbeat.log has new lines, ending in done, and nobody typed anything. That is an agent. After another two minutes, one more line: this Monday is already done, nothing to do.
On a Mac  zsh tools/schedule.sh demo  On Windows  powershell -ExecutionPolicy Bypass -File tools\\schedule.ps1 demo

### Step 30. Set the real clock
The real clock ticks every 30 minutes, every day. Most ticks do nothing, because it is not Monday or this Monday is done. On a Monday it runs your four agents once, for every member, and the second tick finds it done. Your laptop has to be awake for it to run, which is why it ticks rather than going off once at 6am.
On screen: terminal zsh tools/schedule.sh the clock is set: every 1800 seconds it wakes tools/monday.py
You should see: On Monday 21 September, if your laptop is open, heartbeat.log gains a run for monday=2026-09-21 without you doing anything. Check it with zsh tools/schedule.sh status.
On a Mac  zsh tools/schedule.sh  On Windows  powershell -ExecutionPolicy Bypass -File tools\\schedule.ps1

### Step 31. Turn it off on Friday
The clock keeps going after the course. Turn it off before you leave, or it will run your agent every Monday until you do.
On screen: terminal zsh tools/schedule.sh off removed the clock
You should see: The clock is gone. In a company the same four pages would run on Anthropic's Managed Agents, in the cloud, on their own timetable, and no laptop would need to be open. Same pages, a different clock.
On a Mac  zsh tools/schedule.sh off  On Windows  powershell -ExecutionPolicy Bypass -File tools\\schedule.ps1 off

### The runbook, how a Monday runs (agent/RUNBOOK.md)

# How a Monday runs at Gimnasio Zorro. The runbook, not a job description.

Four roles, each on its own page under students/. Carlos pulls the numbers and cannot write
(prepare_week.py is his code). Enrique judges and writes (judge.py runs him headless). Cato doubts
both (cato.py). Rosa counts who came back two weeks later (check_returns.py). Nothing in the scripts
decides who gets written to or what a note says; that is Enrique's, and Cato's to attack.

## The job

Every Monday, for Gimnasio Zorro, find the members who are drifting away from their own pattern,
write each one a short email in Marta's voice off what they said they wanted, send it, and put the
reason and the email on their record. Two weeks later, say how many came back. Never chase someone
whose record gives a reason. When a reply needs a human, ask Marta instead of writing.

Paul, 10 Sep 2026: the agent sends. There is no approval step. Marta is only asked about the odd
case. This week the gym is made up, so a send means the email goes into the email log
(data/email_log.csv) and the card in Attio moves to emailed.

## What starts it

Nobody. Paul, 12 Sep 2026: "We are showing students how to build agents that run on their own, not
commands." So a clock on the laptop wakes agent/monday.py every 30 minutes (agent/schedule.sh
installs it). The runner asks two questions, is it Monday and is this Monday done, and if the answers
are yes and no it runs the four in order. Each one starts only when the one before has left its file.
If a file is missing the run stops there and the heartbeat says where.

Every step writes one line to agent/state/heartbeat.log. That file is the proof a run happened. A
clock that says it is loaded proves nothing, and neither does a note in this file.

Why a tick every 30 minutes rather than an alarm at 6am: a laptop with the lid shut at 6am misses
the alarm and it is not made up. A tick asks "is this Monday done?" whenever the laptop is awake.
In a company the same four pages would run in the cloud, on Anthropic's Managed Agents or the like,
on their own timetable, with no laptop involved.

## How a Monday goes, when the runner does it

1. Carlos. \`python3 agent/prepare_week.py <monday>\` writes \`agent/out/candidates-<monday>.json\`
   with every member's usual rate, last three weeks, notes, and what the agent did for them before.
2. Enrique. \`python3 agent/judge.py <monday>\` reads that file with
   \`messaging/email-voice-and-rules.md\` and \`messaging/messages-by-goal.md\` open. For each member
   he decides one of three things. DRAFT: they are drifting from their own usual pattern, they
   joined more than four weeks ago, they have not been gone eight weeks or more, the record gives no
   reason, and they were not written to in the last four weeks. He writes the note. SKIP: none of
   that is true, and he says why in one line. ASK MARTA: the record or a reply says something only
   she can judge (injured, moved, wants to pause, angry). He writes \`agent/out/decisions-<monday>.json\`,
   one row per member, always the same shape: member_id, name, decision (draft / skip / ask), reason
   (one line quoting the data), email (or empty). He updates \`agent/state/memory.json\` for every
   draft or ask, which is what stops the same person being written to twice.
3. Cato. \`python3 agent/cato.py <monday>\` recounts from the door log himself, decides for each
   member himself, and writes \`agent/out/cato-<monday>.json\` with agree or disagree per row and the
   attack list.
4. Rosa. If there was a Monday with emails fourteen days earlier and she has not checked it,
   \`python3 agent/check_returns.py <that monday>\` reads memory and the door log, counts who came
   back, reads the email log for replies, writes \`agent/out/returns-<that monday>.json\`, and prints
   the line Marta gets. Replies from people who did not come back are listed for her, because those
   are hers to answer.
5. Attio. \`python3 agent/attio.py decisions <monday>\` puts the reason and the email on each card and
   sets the status: emailed for a draft, ask marta for an ask. \`python3 agent/attio.py returns <that
   monday>\` moves Rosa's members to came back or didn't come back. The columns are steady, slipping,
   emailed, ask marta, came back, didn't come back.

To do any of that by hand, for a test, run the script named. To do the whole Monday by hand once:
\`python3 agent/monday.py --monday <monday>\`. A second run on the same Monday does nothing and says
so; \`--force\` runs it again.

## What "the same shape every time" means

Two runs on the same Monday must give the same decisions. A second run on a Monday that has already
been run must draft nothing new. That is the test, and it is run in the room on Tuesday.

### Carlos, the first agent (students/carlos-role.md)

# Carlos. The one who pulls the numbers and cannot write

The first of the four. Four questions, on one page. His code turns four files into one file Enrique
can judge from, the same shape every Monday. He is not allowed to write a word to a member or to
describe a number. In real agent teams the mistakes are almost never in the fetching, they are in the
sentence written next to what was fetched.

## What Carlos produces

One file per Monday, agent/out/candidates-<YYYY-MM-DD>.json, one row per member id in the member
file, with exactly these keys: member_id, first_name, last_name, email, plan, goal, notes, joined,
days_since_joined, weeks_since_joined, visits_per_week_last12 (twelve whole numbers, oldest week
first), usual_per_week, visits_last3, weeks_since_last_visit, previously, last_reply, last_sent, gaps.

A week runs Monday to Sunday and the twelve weeks are the twelve full weeks ending the Sunday before
the Monday being run. Only swipes dated before the Monday and on or after the joined date are
counted; a swipe before joining is not counted and gaps says how many. usual_per_week is visits in
the first nine of the twelve weeks divided by nine, to two decimal places; for a member who joined
after the start of those nine weeks it is visits in the full weeks between joining and the last
three weeks divided by that number of weeks, and empty with a gaps line if there is none.
weeks_since_last_visit is days from the last counted swipe to the Monday divided by seven, whole
weeks; a member with no counted swipe counts as last visited on the day they joined. previously is
the member's entry in agent/state/memory.json copied as is (flagged_on, action, reason), only if its
flagged_on is before the Monday; entries dated the Monday itself are ignored, so a rerun after Enrique
has run still gives the same file. days_since_joined is the Monday minus the joined date;
weeks_since_joined is that divided by seven, whole weeks; visits_last3 is the sum of the last three of
the twelve weekly counts.
last_reply is the reply_text of the email-log row with replied = yes and the latest sent_at before
the Monday, with that sent_at date. last_sent is the latest sent_at before the Monday, or empty.

## Where it lands

That file, and one line for that Monday in agent/out/carlos-run.log: the Monday, the row count, the
path. A rerun of the same Monday replaces its line.

## How he knows he is done

Every row in the member file has a row, every number can be recomputed from the four files by anyone
who checks, and two runs on the same Monday from the same four files give the same file byte for
byte. If any of the four files is missing he writes no file and one log line naming the path.

## What he does not do

He does not judge who is drifting, write notes, touch Attio, round beyond two places, estimate, say
"about", or filter: every member gets a row, whatever their plan or status.

## The handoff

In: the door log, the member file, the email log, the memory file. Out: the file and the log line.
Enrique may not go back to the door log, so if this file is wrong every decision is wrong, and the
only place to fix it is here.

### Enrique, the second agent (students/enrique-role.md)

# Enrique. Marta's member-care assistant

The second of the four. Four questions, on one page. Yours will be the same length.

## What Enrique produces

One decision per row of Carlos's file, every Monday, in one shape: member id, decision (draft, skip,
or ask), the reason in one line quoting the data, and the email or nothing. A draft is an email that
goes out. Nobody approves it first.

Draft when the member is drifting, which means fewer visits in the last three weeks than they
usually make in one week, and they joined more than 28 days ago, and their last visit is less than
eight weeks ago, and previously shows no draft or ask dated within the last 28 days, and neither
stop below applies.

Ask when the notes or the last reply give a health reason in any wording (injured, injury, physio,
surgery, doctor, pregnant, recovering, hold off), say the member has moved away, wants to pause or
cancel, or the reply is angry or says they did not sign up. Ask wins over skip. A goal is not a note.

Skip when the notes or the last reply say the member is elsewhere for a stated time in any wording
(away, holiday, Galicia, travelling, with family for August), or that the slower pattern is by choice
(every other week, all he can manage), or when the draft conditions do not hold.

The email is four sentences or fewer, in Marta's voice, to the member by first name, built on the
messages-by-goal line for the goal on their row, with one ask. Never fees, contracts, renewal or
discounts.

## Where it lands

Four fields on the member's record in Attio: status (emailed or ask marta), last flagged, reason, the email. One decisions
file, agent/out/decisions-<YYYY-MM-DD>.json, which Cato reads. And for every draft or ask, one entry
in agent/state/memory.json keyed on member id: flagged_on (the Monday), action, reason.

## How he knows he is done

The decision rows match Carlos's rows one to one on member id, and a second run on the same Monday
gives the same decision for every row, because previously ignores entries dated that Monday.

## What he does not do

He never opens the door log, does no arithmetic, and never corrects a desk note. Where a desk note
does not fit the member's row, the decision is ask and the reason names both.

## The handoff

Carlos's file in, opened only if agent/out/carlos-run.log has a line for this Monday. The record,
the decisions file and the memory entries out. The two-week check is a separate run that reads the
returns file and writes the outcome.

### Cato, the third agent (students/cato-brief.md)

# Cato. The red team, one page

The third of the four. His job is to assume Carlos and Enrique are wrong and prove it. He is named
after the valet Inspector Clouseau paid to attack him without warning, so he could never go soft.
Build him on Wednesday from this page, and on Thursday afternoon we score him beside the other two.

## What Cato produces

One file, agent/out/cato-<YYYY-MM-DD>.json, from python3 agent/cato.py <monday>, one row per member
id in the member file, fields fixed: member_id, cato_decision (draft, skip, ask), verdict (agree,
disagree), why in one line quoting the data. Plus the attack list: these named checks in this order
and no others, each with rows checked and rows failed, so a check that never ran shows 0 checked and
cannot hide behind 0 failed: carlos_numbers, drifting_rule, joined_rule, eight_week_rule,
written_to_rule, ask_words, skip_words, note_first_name, note_goal, note_one_ask, note_no_money.

His recomputation follows Carlos's page word for word. His own decision uses Enrique's page word for
word, taken from the page and never from Enrique's file. Any weekly count, usual rate, last-three
count or weeks-since-last-visit that differs from his own recomputation is a disagree on that row.
A note that fails a note check is a disagree even when the decision is right, with the failing words
quoted. note_goal means built on the messages-by-goal line for the goal on the member's row, so a
lose-weight note about the member's routine passes. A quote is the weekly counts, the date of the
last swipe, or the words from the notes or reply, never more than a line. Counts, dates and the
first-name and money checks are code; the goal and one-ask checks and the words in why are the model.

## Where it lands

That file, and the field cato_check on the member's record in Attio: the Monday and his line where he
disagrees, empty where he agrees. Marta writes right or wrong into cato_verdict on the same record.
Cato never writes the note.

## How he knows he is done

One row for every member id, the attack list present with all eleven checks, and two runs on the same
Monday give the same verdict on every row. If memory.json, Carlos's file or Enrique's file is missing,
no file and one log line naming the path.

## What he does not do

He never repairs a decision or rewrites a note. He does not read Enrique's file before he has his own
view from Carlos's file and the data. A goal is not a note: "rehab after injury" on the goal line is
why the member joined, and only the notes or the last reply can say injured today. An empty cell in
Carlos's file is not a difference; only a number that differs from his own is.

## How to attack

The door log is data/checkins.csv, the member file data/members.csv, the email log
data/email_log.csv, the write-to history agent/state/memory.json. Written to means what Enrique's
page says: a draft or ask in memory with flagged_on before the Monday and within 28 days. If he
drafted, what would make it a skip or an ask. If he skipped, what would make it a drift. If he asked,
what in the notes or the reply put it in Marta's hands, quoted; if nothing there does, disagree.

## Why he exists

One separate check by an agent with a fresh start is the biggest measured gain in the research on
agent teams. And a checker that logs only what broke cannot be trusted when it is quiet, because a
row nobody opened looks the same as a row that held. That is why the attack list is half of what he
produces.

### Rosa, the fourth agent (students/rosa-role.md)

# Rosa. The one who counts who came back

The fourth of the four. Four questions, on one page. She runs two weeks after Enrique's emails went
out and tells Marta one number: how many of the people we wrote to have been back through the door.
Marta reads Rosa's line every time, because that number is what she wanted the whole thing for. A
gym that sends the emails and never counts who came back does not know if any of it worked.

## What Rosa produces

One file, agent/out/returns-<YYYY-MM-DD>.json, where the date is the Monday the emails went out,
not the Monday she runs. One row per member Enrique wrote to on that Monday, fields fixed:
member_id, name, visits_after (their swipes in the fourteen days from that Monday), returned (true
if visits_after is more than 0), opened, replied, reply_text (from the email log, or empty).
Above the rows: sent_on, checked_on (fourteen days later), written_to (the count of rows), came_back
(the count with returned true).

And one line for Marta, printed and put at the top of the file: "On 31 August we wrote to 65
members. 28 of them have been back in the two weeks since, 43%." Then, for every member who replied
and has not been back, their name and their reply, because those are hers to answer, not the
agent's.

## Where it lands

That file, one line in agent/out/rosa-run.log (the Monday checked, the count written to, the count
back), and on each member's card in Attio the status moves from emailed to came back or didn't come
back. In agent/state/memory.json each of those members gets outcome_checked_on and
returned_within_14_days, so nobody is ever counted twice.

## How she knows she is done

Every member in memory flagged as a draft on that Monday has a row. came_back plus the count of
returned false equals written_to. A second run for the same Monday gives the same file byte for
byte and adds nothing to memory. If memory has nobody written to on that Monday, she writes no file
and one log line saying so.

## What she does not do

She does not write to any member. She does not decide who to write to next; that is Carlos and
Enrique's, next Monday, and they read her outcome from memory. She does not judge a reply; a reply
from someone who has not been back goes to Marta, word for word. She does not read Enrique's
reasons or emails, only who was written to and when. She runs on a Monday two weeks after the
emails, and the runner decides when that is, not her.

### The runner and the clock (students/tools/monday.py, the top of the file)

The runner. This is what the clock starts. On a Monday nobody types anything.

It runs your four agents in order, each one as a page Claude Code reads, and stops the moment one of
them has not left the file its page promised:
  1. carlos.md    writes carlos-out.json
  2. enrique.md   reads carlos-out.json, writes enrique-out.json
  3. cato.md      reads both, writes cato-out.json
  4. rosa.md      two weeks after a Monday with emails, writes rosa-out.json for that Monday
Every step writes one line to heartbeat.log in this folder. The last line for a Monday says done, or
where it stopped. That file is the proof it ran. A clock that says "loaded" proves nothing.

Most ticks of the clock do nothing: it is not a Monday, or this Monday is already done. That is on
purpose. A laptop with the lid closed at 6am misses a 6am alarm, so the runner asks "has this week's
Monday been done?" every time it wakes.

  python3 tools/monday.py                          this week's Monday, once
  python3 tools/monday.py --monday 2026-08-31      a named Monday
  python3 tools/monday.py --member Z0811 --force   one member, again, in the room, to watch it go

### How to write a job an agent can do (students/how-to-write-a-job-an-agent-can-do.md)

# How to write a job an agent can do

Enrique's page is the finished thing. This is how you get to a page like it. Seven steps, in
order, and you will do all seven for each of your agents this week.

## 1. Decide what it produces before anything else

Name the thing, and fix its shape. Not "reviews the members" but "one row per member: id,
decision, reason, note or nothing". If two runs could give different shapes, it is not a thing
yet, it is an activity, and an activity cannot be checked. Enrique's shape is four fields and
never changes.

## 2. Name where it lands, and make sure someone reads there

A surface the owner already looks at, named exactly. Enrique lands on the member's record in
Attio because Marta reads Attio. Work that lands in a folder nobody opens has not happened, and
the log will still say success.

## 3. Write the done condition so it can fail

"Every member in the door log has a row, the rows are on the records, and a second run on the
same Monday adds nothing." Each part of that can be checked and each part can be false. "When
the members have been reviewed" cannot fail, so it is not a condition.

## 4. Write what it does not do, and split the work at the line where mistakes happen

In real agent teams the mistakes are almost never in the fetching. They are in the sentence
written next to the number. So the one who computes cannot write, and the one who writes cannot
compute. Carlos does the arithmetic with code and copies the result. Enrique never opens the
door log. Put the boundary in the job in plain words, because an agent will drift across it
otherwise and every step after will look fine.

## 5. Name the handoffs, both sides

For every file, field or record that carries work in or out, say what it is and check that the
other agent's page tells it to read that thing. A handoff where one side names a destination and
the other side was never told to look breaks silently, and it looks identical to a working one
from either side. Enrique's page names Carlos's file coming in and Marta's record going out, and
Carlos's page names the same file.

## 6. Keep it on one page, and take a line out for every line you add

A list of instructions is obeyed less the longer it gets, and the drop starts early. A job that
needs a page of steps to run is not written yet. Everything about how the run happens, which
script, which file, which order, lives in a separate runbook, not in the job.

## 7. Run it, count it, attack it, change one line, run it again

Run the job on a Monday you have an answer key for and count the decisions that match. Then let
Cato attack the decisions from the data, and attack the job itself with the four questions above,
assuming the agent is literal, lazy and honest. Every finding is one line to change in the job.
Change it, run the same Monday again, and see the number move. Stop when the number holds and
Cato's attack list comes back with nothing that breaks. That is what "it works" means: not that
it ran, but that you counted.

### The set-up sheet (students/setup-before-monday.md)

# Before Monday 14 September. Please do these four things

You are going to build a working AI agent for a gym during the week, in a team of three, and on
Friday you will show it running and tell us how well it did. To start building on Monday afternoon
you need four things set up before you walk in. Each one takes a few minutes. Do them this week,
not on the bus.

## 1. Claude

Your access to Claude for the week is being arranged by Smurfit; Julie will confirm the details.
Whatever plan it is, make sure you can log in at claude.ai before Monday and that you know your
password. On Monday afternoon you will be building with Claude Code, which runs on your laptop in
a terminal. Install it now so Monday is not spent installing. Go to claude.ai/code and follow the
install steps for your machine (Mac or Windows). Open a terminal, type claude, log in with the
same account. If it opens and says hello, you are done.

## 2. Attio

Attio is the CRM the gym's members live in, and your agent will read and write it. Sign up for a
free account at attio.com with your university email. One person per team creates the workspace
and names it after your team (Zorro Team 4, say), then invites the other two. The free plan allows
three people, which is why teams are three. Do not pay for anything.

## 3. The gym

You will receive a folder called Gimnasio Zorro on Monday morning. It has the members, fourteen
weeks of door swipes, and three short pages about the gym and how its owner writes. Have a place
on your laptop to put it. That is all.

## 4. Your laptop

Charged, with a terminal you can open (Terminal on a Mac, Windows Terminal or PowerShell on
Windows), and enough battery for a full day. The room has power but not at every seat.

## What you will build

Every Monday, your agent reads the gym's door log and the member records, finds the members who
are drifting away, writes each one a short personal email, sends it, and records what it did in
Attio. Two weeks later it looks again and tells the owner how many came back. On
Friday you present the number your agent scored on fifty marked members, and your two worst
mistakes.

## If something will not install

Tell Julie before Monday, not on Monday. If Claude Code will not go on your machine we can still
run Monday in the browser, but you will want it working by Tuesday.

### The gym (messaging/gimnasio-zorro.md)

# Gimnasio Zorro

Fictional. Built for the UCD x IE week, September 2026. Every person in it is made up.

Gimnasio Zorro is a neighbourhood gym in Chamberí, Madrid. One floor of weights and machines, a
studio for classes, open 6am to 11pm. About 900 members. The owner is Marta Ferrer. She opened it
nine years ago, still works the desk most mornings, and knows a lot of members by name. Three staff
on the floor, two class instructors, nobody in an office.

What the gym is for, in Marta's words: this is the gym you actually keep going to. Not the cheapest
in Madrid, not the biggest. The one where someone notices when you have not been in.

That last line is the positioning, and it is the problem too. Marta knows that a member who stops
coming for a few weeks tends not to renew. She knows it from nine years of watching it happen. She
does not have the hours to go through 900 members every Monday, work out who is drifting, and write
each of them a proper note. So the thing the gym is for is the thing the gym cannot do.

The members. Roughly a quarter joined to lose weight, a fifth to build muscle, a fifth for general
fitness. The rest are training for something (a half marathon, a wedding, a ski trip), managing
stress and sleep, getting stronger as they get older, or coming back after an injury. Each member
told the gym their goal when they joined and it is on their record. Some records carry notes from
the desk: away in August, knee injury, comes once a fortnight and that is fine.

The plans. Monthly, annual, off-peak mornings, student. The plan matters less than the pattern.
An off-peak member who came every morning and has stopped is a bigger loss than an annual member
who always came once a fortnight.

What the agent does for Marta. Every Monday it reads the door log and the member records, finds the
members who are drifting from their own pattern, writes each one a short personal email in Marta's
voice off what they said they wanted, sends it, and puts the reason and the email on the member's
record. Two weeks later it looks again and tells her how many came back. Nobody approves the emails
first. It never chases someone whose record says injured or away. When a reply says
something the agent cannot judge, it asks Marta.

### How Marta writes, and the email rules (messaging/email-voice-and-rules.md)

# The emails. Marta's voice and the rules the agent follows

The students get this file. They do not have to work out the positioning or the messaging; that
would eat the week. Paul talks about why the quality of these emails matters. The agent has to
write to it.

## Who is writing

Marta Ferrer, the owner. She is writing to one person she knows, not to a list. She has noticed
they have not been in. She is not selling anything and she is not guilt-tripping anyone.

## What every email does

It says who it is from, in the first line, and that Marta noticed. It names the thing the member
said they wanted, in their own words off the record. It makes one ask, small and specific: a class
this week, a morning, a reply. It ends. Four or five sentences. Under eighty words.

## What an email never does

It never says "we miss you". It never mentions the membership fee, the contract, or renewal. It
never asks why they stopped. It never offers a discount. It never lists three things they could do.
It never uses the word journey. It never guesses at a reason the record does not give.

It never names the member's private life. No wedding, no holiday, no family member, no health
matter, no date. A gym writing about someone's sister's wedding is intrusive, however well meant.
The email refers to the goal the member gave when they joined in general words only: "what you
were working towards", "the goal you set when you joined". Warm, but professional. Paul, 11 Sep 2026.

## When the agent does not write

The record says away, on holiday, travelling. The record says injured, physio, surgery, doctor,
pregnant. The member joined less than four weeks ago. The member has been gone eight weeks or
more. The member has always come once a fortnight. A reply has come in that the agent cannot judge.
In every one of those cases the agent writes nothing and tells Marta why, in one line.

## A bad one

Hi Rubén,

We have missed you at Gimnasio Zorro! It has been a while since your last visit and we wanted to
check in. Remember, consistency is key on your fitness journey. We have lots of great classes this
month, plus a special offer on personal training. Don't forget your membership renews on the 30th.
Hope to see you soon!

The Zorro team

Why it is bad. Nobody wrote it. It does not know who Rubén is or what he wanted. Three asks and a
discount. It mentions the renewal, which is the one thing that makes a drifting member cancel.

## A good one

Hi Rubén,

Marta here. I noticed you have not been in since the middle of August. You told me when you joined
what you were working towards, and a few weeks off makes that harder. Tuesday at 7 there is a small
class that would suit, and I will be on the desk if you want a word first. Come in this week?

Marta

Why it is good. One person to one person. It reminds him he had a goal without naming his private
life. One ask with a day and a time. No fee, no guilt, no offer. He can say yes in two words.

### What to say for each goal (messaging/messages-by-goal.md)

# What Marta says to each kind of member

The goal is on the member's record. The agent uses the line for that goal as the middle of the
email, in Marta's words, and adds the one ask. The email never names the member's private life (the
rule is in email-voice-and-rules.md): the goal is referred to in general words, never the event, the
person or the health matter behind it. Nothing in this file is a script to paste; it is what
the note has to be about.

Lose weight. Do not mention weight. Talk about the routine they had built and the mornings or
evenings they used to come. The ask is a specific slot they used to keep.

Build muscle. They care about not losing what they built. Say the floor has been quiet in the
evenings and their bench is free. The ask is a session this week, not a programme.

General fitness. These are the easiest to lose because nothing is pulling them in. Name the class
or the time they used to come and say it is still there. The ask is one visit.

Stress and sleep. They joined because life was heavy. If they have stopped, life probably got
heavier. Keep it gentle, no push. The ask is a quiet morning or a stretch class, and it is fine to
say no.

Get fit for an event. The event is on the record with a date, and the email never names it, never
names who it is for, and never counts the weeks to it. Say they set themselves a goal with a date
on it when they joined, and that there is still time to make a difference. The ask is a plan for the
weeks left, and Marta offering ten minutes at the desk to write it.

Strength as I get older. Usually a member over sixty who was coming steadily. Say plainly that a
few weeks off costs more at their age and comes back slower, because that is true and they know
it. The ask is a morning this week.

Rehab after injury. Check the record first. If the notes say the injury is back, do not write.
If the record is silent, the note asks how the recovery is going and offers a slot with the
instructor who knows their case. The ask is a reply, not a visit.

### Three members a quick answer gets wrong (packs/vet-three-planted-cases.md)

# Monday 11:15. The three planted cases

Put each on screen in this order. Row from members.csv, then the visits per week for weeks 1 to 12 (8 Jun to 30 Aug), then ask the model.

## The fortnightly regular

Lucía Rodríguez, Z0693. Joined 2024-06-18. Plan Monthly. Goal: build muscle. Notes: Comes every other week, that is her pattern.

Visits per week, weeks 1 to 12: 1 0 1 0 1 0 1 0 1 0 1 0

Ask: is this member lapsing? The model will say yes off the two-week gap. The pattern says once a fortnight since June, and the note says so too.

## The August gap with a note

Mateo Blanco, Z0776. Joined 2026-03-04. Plan Annual. Goal: lose weight. Notes: In Galicia with family for August.

Visits per week, weeks 1 to 12: 2 3 3 3 2 1 3 3 2 0 0 0

Ask: is this member lapsing? Three weeks at zero in August. The note says away. Not a lapse, and no email.

## The email with the wrong goal

Cristina Ramírez, Z0830. Joined 2025-08-11. Plan Annual. Goal: lose weight. Notes: (none)

Visits per week, weeks 1 to 12: 4 4 3 2 3 5 4 3 3 0 0 0

Ask the model to write the note. Then show one that talks about building muscle. This member said lose weight. Same shape, wrong person.

### The project README (README.md)

# Gimnasio Zorro, the dummy gym for the UCD x IE week

One fictional gym in Madrid, 900 members, fourteen weeks of door log, built so that a class of
business students can build an agent for it in a week and count how well it works. Nothing in
here is real. Every name, email and check-in is generated by build_gym.py, and the same seed gives
the same gym every time.

The job the agent does. Every Monday it reads the door log and the member records, finds the
members who are drifting away from their own pattern, writes each a short personal email in the
owner's voice off what they said they wanted, sends it, and puts the reason and the email on the
member's record in Attio. Two weeks later it reads the door log again and tells the owner how many
came back. Nobody approves the emails first; the owner is only asked about the odd case. This week
the send is pretend: the email goes into the email log, because every member is made up.

It is four agents, not one, and nobody starts them. Carlos counts (agent/prepare_week.py), Enrique
writes and sends (agent/judge.py), Cato checks the other two (agent/cato.py), Rosa counts who came
back two weeks later (agent/check_returns.py). A clock on the laptop wakes agent/monday.py every 30
minutes; on a Monday it runs the four in order, each when the one before has left its file, and
writes one line per step to agent/state/heartbeat.log. agent/schedule.sh sets the clock. The
students' copy of the runner and the clock is in students/tools and goes out in the zip.

The timeline. Week 1 starts Monday 8 June 2026. The agent's first run is as of Monday 31 August,
the start of week 13. Its second run is as of Monday 14 September, the first morning of the
course, and reads weeks 13 and 14 to see who came back.

What is in data. members.csv is one row per member, the way a gym's CRM would hold it, with the
goal they gave when they joined and any notes from the desk. checkins.csv is one row per door
swipe, the way a door system exports it. email_log.csv is what happened when the week 13 notes
went out, opened or not, replied or not, and the reply text, so the agent has something to stop
on.

What is in eval. answer_key_all.csv has every member with the planted pattern, whether the agent
should flag them at run 1, the reason, and whether they came back in weeks 13 and 14. It is for
the teacher. fifty_cases.csv is the fifty marked members the students score their agent against on
Thursday. It is handed out on Thursday and not before.

What is in messaging. The gym, the owner and the positioning in one page. The voice the emails are
written in and the rules the agent follows, with a bad example and a good one. And what the note
says for each kind of goal. Students get these files rather than writing them, because the
positioning work would take the week; Paul talks about why they matter.

The planted patterns, and what a fair rule finds. A rule that compares each member to their own
usual rate over weeks 1 to 9, and reads the notes, matches the answer key on all 900. The same
rule without the notes gets 38 wrong, all of them people who were away or injured. That gap is
the Monday morning lesson.

The numbers as of 5 September. 900 members, 65 flagged at run 1, 28 of those back in weeks 13 to
14. Rerun build_gym.py and they hold.`;
