/* Generated by the gym repo on 11 Sep 2026 from the student pages, the runbook and the messaging
   pack: ~/projects/clients/ucd/ie-week-gym-agent. Do not edit here; edit the pages and regenerate. */

export const ZORRO_KNOWLEDGE = `### The runbook, how a Monday runs (agent/RUNBOOK.md)

# How a Monday runs at Gimnasio Zorro. The runbook, not a job description.

Three roles, each on its own page under students/. Carlos pulls the numbers and cannot write
(prepare_week.py is his code). Enrique judges and writes (judge.py runs him headless). Cato doubts
both (cato.py). check_returns.py is the two-week check. Nothing in the scripts decides who gets
written to or what a note says; that is Enrique's, and Cato's to attack.

## The job

Every Monday, for Gimnasio Zorro, find the members who are drifting away from their own pattern,
write each one a short email in Marta's voice off what they said they wanted, send it, and put the
reason and the email on their record. Two weeks later, say how many came back. Never chase someone
whose record gives a reason. When a reply needs a human, ask Marta instead of writing.

Paul, 10 Sep 2026: the agent sends. There is no approval step. Marta is only asked about the odd
case. This week the gym is made up, so a send means the email goes into the email log
(data/email_log.csv) and the card in Attio moves to emailed.

## How a Monday goes

1. Run \`python3 agent/prepare_week.py <monday>\`. It writes \`agent/out/candidates-<monday>.json\`
   with every member's usual rate, last three weeks, notes, and what the agent did for them before.
2. Read that file with \`messaging/email-voice-and-rules.md\` and \`messaging/messages-by-goal.md\`
   open. For each member decide one of three things. DRAFT: they are drifting from their own usual
   pattern, they joined more than four weeks ago, they have not been gone eight weeks or more,
   the record gives no reason, and they were not written to in the last four weeks. Write the note.
   SKIP: none of that is true. Say why in one line. ASK MARTA: the record or a reply says something
   only she can judge (injured, moved, wants to pause, angry). Say what and why.
3. Write the decisions to \`agent/out/decisions-<monday>.json\`, one row per member, in this shape:
   member_id, name, decision (draft / skip / ask), reason (one line quoting the data), email (or
   empty). The shape never changes.
4. Update \`agent/state/memory.json\`: for every draft or ask, record flagged_on, action, name, and
   the reason. This is what stops the same person being written to twice.
5. Put the reason and the email on the member's record in Attio and set their status: emailed for a
   draft, ask marta for an ask. The columns are steady, slipping, emailed, ask marta, came back,
   didn't come back.

## Two weeks later

Run \`python3 agent/check_returns.py <that monday>\`. It reads memory and the door log, counts who
came back, reads the email log for replies, and prints the line Marta gets. Replies from people who
did not come back are listed for her, because those are hers to answer.

## What "the same shape every time" means

Two runs on the same Monday must give the same decisions. A second run on a Monday that has already
been run must draft nothing new. That is the test, and it is run in the room on Tuesday.

### Carlos, the first agent (students/carlos-role.md)

# Carlos. The one who pulls the numbers and cannot write

The first of the three. Four questions, on one page. His code turns four files into one file Enrique
can judge from, the same shape every Monday. He is not allowed to write a word to a member or to
describe a number. In real agent teams the mistakes are almost never in the fetching, they are in the
sentence written next to what was fetched.

## What Carlos produces

One file per Monday, agent/out/candidates-<YYYY-MM-DD>.json, one row per member id in the member
file, with exactly these keys: member_id, first_name, last_name, email, plan, goal, notes, joined,
days_since_joined, weeks_since_joined, visits_per_week_last12 (twelve whole numbers, oldest week
first), usual_per_week, visits_last3, weeks_since_last_visit, previously, last_reply, last_sent, gaps.

A week runs Monday to Sunday and the twelve weeks are the twelve full weeks ending the Sunday before
the Monday being run. Only swipes dated before the Monday and on or after the joined date are
counted; a swipe before joining is not counted and gaps says how many. usual_per_week is visits in
the first nine of the twelve weeks divided by nine, to two decimal places; for a member who joined
after the start of those nine weeks it is visits in the full weeks between joining and the last
three weeks divided by that number of weeks, and empty with a gaps line if there is none.
weeks_since_last_visit is days from the last counted swipe to the Monday divided by seven, whole
weeks; a member with no counted swipe counts as last visited on the day they joined. previously is
the member's entry in agent/state/memory.json copied as is (flagged_on, action, reason), only if its
flagged_on is before the Monday; entries dated the Monday itself are ignored, so a rerun after Enrique
has run still gives the same file. days_since_joined is the Monday minus the joined date;
weeks_since_joined is that divided by seven, whole weeks; visits_last3 is the sum of the last three of
the twelve weekly counts.
last_reply is the reply_text of the email-log row with replied = yes and the latest sent_at before
the Monday, with that sent_at date. last_sent is the latest sent_at before the Monday, or empty.

## Where it lands

That file, and one line for that Monday in agent/out/carlos-run.log: the Monday, the row count, the
path. A rerun of the same Monday replaces its line.

## How he knows he is done

Every row in the member file has a row, every number can be recomputed from the four files by anyone
who checks, and two runs on the same Monday from the same four files give the same file byte for
byte. If any of the four files is missing he writes no file and one log line naming the path.

## What he does not do

He does not judge who is drifting, write notes, touch Attio, round beyond two places, estimate, say
"about", or filter: every member gets a row, whatever their plan or status.

## The handoff

In: the door log, the member file, the email log, the memory file. Out: the file and the log line.
Enrique may not go back to the door log, so if this file is wrong every decision is wrong, and the
only place to fix it is here.

### Enrique, the second agent (students/enrique-role.md)

# Enrique. Marta's member-care assistant

The second of the three. Four questions, on one page. Yours will be the same length.

## What Enrique produces

One decision per row of Carlos's file, every Monday, in one shape: member id, decision (draft, skip,
or ask), the reason in one line quoting the data, and the email or nothing. A draft is an email that
goes out. Nobody approves it first.

Draft when the member is drifting, which means fewer visits in the last three weeks than they
usually make in one week, and they joined more than 28 days ago, and their last visit is less than
eight weeks ago, and previously shows no draft or ask dated within the last 28 days, and neither
stop below applies.

Ask when the notes or the last reply give a health reason in any wording (injured, injury, physio,
surgery, doctor, pregnant, recovering, hold off), say the member has moved away, wants to pause or
cancel, or the reply is angry or says they did not sign up. Ask wins over skip. A goal is not a note.

Skip when the notes or the last reply say the member is elsewhere for a stated time in any wording
(away, holiday, Galicia, travelling, with family for August), or that the slower pattern is by choice
(every other week, all he can manage), or when the draft conditions do not hold.

The email is four sentences or fewer, in Marta's voice, to the member by first name, built on the
messages-by-goal line for the goal on their row, with one ask. Never fees, contracts, renewal or
discounts.

## Where it lands

Four fields on the member's record in Attio: status (emailed or ask marta), last flagged, reason, the email. One decisions
file, agent/out/decisions-<YYYY-MM-DD>.json, which Cato reads. And for every draft or ask, one entry
in agent/state/memory.json keyed on member id: flagged_on (the Monday), action, reason.

## How he knows he is done

The decision rows match Carlos's rows one to one on member id, and a second run on the same Monday
gives the same decision for every row, because previously ignores entries dated that Monday.

## What he does not do

He never opens the door log, does no arithmetic, and never corrects a desk note. Where a desk note
does not fit the member's row, the decision is ask and the reason names both.

## The handoff

Carlos's file in, opened only if agent/out/carlos-run.log has a line for this Monday. The record,
the decisions file and the memory entries out. The two-week check is a separate run that reads the
returns file and writes the outcome.

### Cato, the third agent (students/cato-brief.md)

# Cato. The red team, one page

The third of the three. His job is to assume Carlos and Enrique are wrong and prove it. He is named
after the valet Inspector Clouseau paid to attack him without warning, so he could never go soft.
Build him on Wednesday from this page, and on Thursday afternoon we score him beside the other two.

## What Cato produces

One file, agent/out/cato-<YYYY-MM-DD>.json, from python3 agent/cato.py <monday>, one row per member
id in the member file, fields fixed: member_id, cato_decision (draft, skip, ask), verdict (agree,
disagree), why in one line quoting the data. Plus the attack list: these named checks in this order
and no others, each with rows checked and rows failed, so a check that never ran shows 0 checked and
cannot hide behind 0 failed: carlos_numbers, drifting_rule, joined_rule, eight_week_rule,
written_to_rule, ask_words, skip_words, note_first_name, note_goal, note_one_ask, note_no_money.

His recomputation follows Carlos's page word for word. His own decision uses Enrique's page word for
word, taken from the page and never from Enrique's file. Any weekly count, usual rate, last-three
count or weeks-since-last-visit that differs from his own recomputation is a disagree on that row.
A note that fails a note check is a disagree even when the decision is right, with the failing words
quoted. note_goal means built on the messages-by-goal line for the goal on the member's row, so a
lose-weight note about the member's routine passes. A quote is the weekly counts, the date of the
last swipe, or the words from the notes or reply, never more than a line. Counts, dates and the
first-name and money checks are code; the goal and one-ask checks and the words in why are the model.

## Where it lands

That file, and the field cato_check on the member's record in Attio: the Monday and his line where he
disagrees, empty where he agrees. Marta writes right or wrong into cato_verdict on the same record.
Cato never writes the note.

## How he knows he is done

One row for every member id, the attack list present with all eleven checks, and two runs on the same
Monday give the same verdict on every row. If memory.json, Carlos's file or Enrique's file is missing,
no file and one log line naming the path.

## What he does not do

He never repairs a decision or rewrites a note. He does not read Enrique's file before he has his own
view from Carlos's file and the data. A goal is not a note: "rehab after injury" on the goal line is
why the member joined, and only the notes or the last reply can say injured today. An empty cell in
Carlos's file is not a difference; only a number that differs from his own is.

## How to attack

The door log is data/checkins.csv, the member file data/members.csv, the email log
data/email_log.csv, the write-to history agent/state/memory.json. Written to means what Enrique's
page says: a draft or ask in memory with flagged_on before the Monday and within 28 days. If he
drafted, what would make it a skip or an ask. If he skipped, what would make it a drift. If he asked,
what in the notes or the reply put it in Marta's hands, quoted; if nothing there does, disagree.

## Why he exists

One separate check by an agent with a fresh start is the biggest measured gain in the research on
agent teams. And a checker that logs only what broke cannot be trusted when it is quiet, because a
row nobody opened looks the same as a row that held. That is why the attack list is half of what he
produces.

### How to write a job an agent can do (students/how-to-write-a-job-an-agent-can-do.md)

# How to write a job an agent can do

Enrique's page is the finished thing. This is how you get to a page like it. Seven steps, in
order, and you will do all seven for each of your agents this week.

## 1. Decide what it produces before anything else

Name the thing, and fix its shape. Not "reviews the members" but "one row per member: id,
decision, reason, note or nothing". If two runs could give different shapes, it is not a thing
yet, it is an activity, and an activity cannot be checked. Enrique's shape is four fields and
never changes.

## 2. Name where it lands, and make sure someone reads there

A surface the owner already looks at, named exactly. Enrique lands on the member's record in
Attio because Marta reads Attio. Work that lands in a folder nobody opens has not happened, and
the log will still say success.

## 3. Write the done condition so it can fail

"Every member in the door log has a row, the rows are on the records, and a second run on the
same Monday adds nothing." Each part of that can be checked and each part can be false. "When
the members have been reviewed" cannot fail, so it is not a condition.

## 4. Write what it does not do, and split the work at the line where mistakes happen

In real agent teams the mistakes are almost never in the fetching. They are in the sentence
written next to the number. So the one who computes cannot write, and the one who writes cannot
compute. Carlos does the arithmetic with code and copies the result. Enrique never opens the
door log. Put the boundary in the job in plain words, because an agent will drift across it
otherwise and every step after will look fine.

## 5. Name the handoffs, both sides

For every file, field or record that carries work in or out, say what it is and check that the
other agent's page tells it to read that thing. A handoff where one side names a destination and
the other side was never told to look breaks silently, and it looks identical to a working one
from either side. Enrique's page names Carlos's file coming in and Marta's record going out, and
Carlos's page names the same file.

## 6. Keep it on one page, and take a line out for every line you add

A list of instructions is obeyed less the longer it gets, and the drop starts early. A job that
needs a page of steps to run is not written yet. Everything about how the run happens, which
script, which file, which order, lives in a separate runbook, not in the job.

## 7. Run it, count it, attack it, change one line, run it again

Run the job on a Monday you have an answer key for and count the decisions that match. Then let
Cato attack the decisions from the data, and attack the job itself with the four questions above,
assuming the agent is literal, lazy and honest. Every finding is one line to change in the job.
Change it, run the same Monday again, and see the number move. Stop when the number holds and
Cato's attack list comes back with nothing that breaks. That is what "it works" means: not that
it ran, but that you counted.

### The set-up sheet (students/setup-before-monday.md)

# Before Monday 14 September. Please do these four things

You are going to build a working AI agent for a gym during the week, in a team of three, and on
Friday you will show it running and tell us how well it did. To start building on Monday afternoon
you need four things set up before you walk in. Each one takes a few minutes. Do them this week,
not on the bus.

## 1. Claude

Your access to Claude for the week is being arranged by Smurfit; Julie will confirm the details.
Whatever plan it is, make sure you can log in at claude.ai before Monday and that you know your
password. On Monday afternoon you will be building with Claude Code, which runs on your laptop in
a terminal. Install it now so Monday is not spent installing. Go to claude.ai/code and follow the
install steps for your machine (Mac or Windows). Open a terminal, type claude, log in with the
same account. If it opens and says hello, you are done.

## 2. Attio

Attio is the CRM the gym's members live in, and your agent will read and write it. Sign up for a
free account at attio.com with your university email. One person per team creates the workspace
and names it after your team (Zorro Team 4, say), then invites the other two. The free plan allows
three people, which is why teams are three. Do not pay for anything.

## 3. The gym

You will receive a folder called Gimnasio Zorro on Monday morning. It has the members, fourteen
weeks of door swipes, and three short pages about the gym and how its owner writes. Have a place
on your laptop to put it. That is all.

## 4. Your laptop

Charged, with a terminal you can open (Terminal on a Mac, Windows Terminal or PowerShell on
Windows), and enough battery for a full day. The room has power but not at every seat.

## What you will build

Every Monday, your agent reads the gym's door log and the member records, finds the members who
are drifting away, writes each one a short personal email, sends it, and records what it did in
Attio. Two weeks later it looks again and tells the owner how many came back. On
Friday you present the number your agent scored on fifty marked members, and your two worst
mistakes.

## If something will not install

Tell Julie before Monday, not on Monday. If Claude Code will not go on your machine we can still
run Monday in the browser, but you will want it working by Tuesday.

### The gym (messaging/gimnasio-zorro.md)

# Gimnasio Zorro

Fictional. Built for the UCD x IE week, September 2026. Every person in it is made up.

Gimnasio Zorro is a neighbourhood gym in Chamberí, Madrid. One floor of weights and machines, a
studio for classes, open 6am to 11pm. About 900 members. The owner is Marta Ferrer. She opened it
nine years ago, still works the desk most mornings, and knows a lot of members by name. Three staff
on the floor, two class instructors, nobody in an office.

What the gym is for, in Marta's words: this is the gym you actually keep going to. Not the cheapest
in Madrid, not the biggest. The one where someone notices when you have not been in.

That last line is the positioning, and it is the problem too. Marta knows that a member who stops
coming for a few weeks tends not to renew. She knows it from nine years of watching it happen. She
does not have the hours to go through 900 members every Monday, work out who is drifting, and write
each of them a proper note. So the thing the gym is for is the thing the gym cannot do.

The members. Roughly a quarter joined to lose weight, a fifth to build muscle, a fifth for general
fitness. The rest are training for something (a half marathon, a wedding, a ski trip), managing
stress and sleep, getting stronger as they get older, or coming back after an injury. Each member
told the gym their goal when they joined and it is on their record. Some records carry notes from
the desk: away in August, knee injury, comes once a fortnight and that is fine.

The plans. Monthly, annual, off-peak mornings, student. The plan matters less than the pattern.
An off-peak member who came every morning and has stopped is a bigger loss than an annual member
who always came once a fortnight.

What the agent does for Marta. Every Monday it reads the door log and the member records, finds the
members who are drifting from their own pattern, writes each one a short personal email in Marta's
voice off what they said they wanted, sends it, and puts the reason and the email on the member's
record. Two weeks later it looks again and tells her how many came back. Nobody approves the emails
first. It never chases someone whose record says injured or away. When a reply says
something the agent cannot judge, it asks Marta.

### How Marta writes, and the email rules (messaging/email-voice-and-rules.md)

# The emails. Marta's voice and the rules the agent follows

The students get this file. They do not have to work out the positioning or the messaging; that
would eat the week. Paul talks about why the quality of these emails matters. The agent has to
write to it.

## Who is writing

Marta Ferrer, the owner. She is writing to one person she knows, not to a list. She has noticed
they have not been in. She is not selling anything and she is not guilt-tripping anyone.

## What every email does

It says who it is from, in the first line, and that Marta noticed. It names the thing the member
said they wanted, in their own words off the record. It makes one ask, small and specific: a class
this week, a morning, a reply. It ends. Four or five sentences. Under eighty words.

## What an email never does

It never says "we miss you". It never mentions the membership fee, the contract, or renewal. It
never asks why they stopped. It never offers a discount. It never lists three things they could do.
It never uses the word journey. It never guesses at a reason the record does not give.

It never names the member's private life. No wedding, no holiday, no family member, no health
matter, no date. A gym writing about someone's sister's wedding is intrusive, however well meant.
The email refers to the goal the member gave when they joined in general words only: "what you
were working towards", "the goal you set when you joined". Warm, but professional. Paul, 11 Sep 2026.

## When the agent does not write

The record says away, on holiday, travelling. The record says injured, physio, surgery, doctor,
pregnant. The member joined less than four weeks ago. The member has been gone eight weeks or
more. The member has always come once a fortnight. A reply has come in that the agent cannot judge.
In every one of those cases the agent writes nothing and tells Marta why, in one line.

## A bad one

Hi Rubén,

We have missed you at Gimnasio Zorro! It has been a while since your last visit and we wanted to
check in. Remember, consistency is key on your fitness journey. We have lots of great classes this
month, plus a special offer on personal training. Don't forget your membership renews on the 30th.
Hope to see you soon!

The Zorro team

Why it is bad. Nobody wrote it. It does not know who Rubén is or what he wanted. Three asks and a
discount. It mentions the renewal, which is the one thing that makes a drifting member cancel.

## A good one

Hi Rubén,

Marta here. I noticed you have not been in since the middle of August. You told me when you joined
what you were working towards, and a few weeks off makes that harder. Tuesday at 7 there is a small
class that would suit, and I will be on the desk if you want a word first. Come in this week?

Marta

Why it is good. One person to one person. It reminds him he had a goal without naming his private
life. One ask with a day and a time. No fee, no guilt, no offer. He can say yes in two words.

### What to say for each goal (messaging/messages-by-goal.md)

# What Marta says to each kind of member

The goal is on the member's record. The agent uses the line for that goal as the middle of the
email, in Marta's words, and adds the one ask. The email never names the member's private life (the
rule is in email-voice-and-rules.md): the goal is referred to in general words, never the event, the
person or the health matter behind it. Nothing in this file is a script to paste; it is what
the note has to be about.

Lose weight. Do not mention weight. Talk about the routine they had built and the mornings or
evenings they used to come. The ask is a specific slot they used to keep.

Build muscle. They care about not losing what they built. Say the floor has been quiet in the
evenings and their bench is free. The ask is a session this week, not a programme.

General fitness. These are the easiest to lose because nothing is pulling them in. Name the class
or the time they used to come and say it is still there. The ask is one visit.

Stress and sleep. They joined because life was heavy. If they have stopped, life probably got
heavier. Keep it gentle, no push. The ask is a quiet morning or a stretch class, and it is fine to
say no.

Get fit for an event. The event is on the record with a date, and the email never names it, never
names who it is for, and never counts the weeks to it. Say they set themselves a goal with a date
on it when they joined, and that there is still time to make a difference. The ask is a plan for the
weeks left, and Marta offering ten minutes at the desk to write it.

Strength as I get older. Usually a member over sixty who was coming steadily. Say plainly that a
few weeks off costs more at their age and comes back slower, because that is true and they know
it. The ask is a morning this week.

Rehab after injury. Check the record first. If the notes say the injury is back, do not write.
If the record is silent, the note asks how the recovery is going and offers a slot with the
instructor who knows their case. The ask is a reply, not a visit.

### Three members a quick answer gets wrong (packs/vet-three-planted-cases.md)

# Monday 11:15. The three planted cases

Put each on screen in this order. Row from members.csv, then the visits per week for weeks 1 to 12 (8 Jun to 30 Aug), then ask the model.

## The fortnightly regular

Lucía Rodríguez, Z0693. Joined 2024-06-18. Plan Monthly. Goal: build muscle. Notes: Comes every other week, that is her pattern.

Visits per week, weeks 1 to 12: 1 0 1 0 1 0 1 0 1 0 1 0

Ask: is this member lapsing? The model will say yes off the two-week gap. The pattern says once a fortnight since June, and the note says so too.

## The August gap with a note

Mateo Blanco, Z0776. Joined 2026-03-04. Plan Annual. Goal: lose weight. Notes: In Galicia with family for August.

Visits per week, weeks 1 to 12: 2 3 3 3 2 1 3 3 2 0 0 0

Ask: is this member lapsing? Three weeks at zero in August. The note says away. Not a lapse, and no email.

## The email with the wrong goal

Cristina Ramírez, Z0830. Joined 2025-08-11. Plan Annual. Goal: lose weight. Notes: (none)

Visits per week, weeks 1 to 12: 4 4 3 2 3 5 4 3 3 0 0 0

Ask the model to write the note. Then show one that talks about building muscle. This member said lose weight. Same shape, wrong person.

### The project README (README.md)

# Gimnasio Zorro, the dummy gym for the UCD x IE week

One fictional gym in Madrid, 900 members, fourteen weeks of door log, built so that a class of
business students can build an agent for it in a week and count how well it works. Nothing in
here is real. Every name, email and check-in is generated by build_gym.py, and the same seed gives
the same gym every time.

The job the agent does. Every Monday it reads the door log and the member records, finds the
members who are drifting away from their own pattern, writes each a short personal email in the
owner's voice off what they said they wanted, sends it, and puts the reason and the email on the
member's record in Attio. Two weeks later it reads the door log again and tells the owner how many
came back. Nobody approves the emails first; the owner is only asked about the odd case. This week
the send is pretend: the email goes into the email log, because every member is made up.

The timeline. Week 1 starts Monday 8 June 2026. The agent's first run is as of Monday 31 August,
the start of week 13. Its second run is as of Monday 14 September, the first morning of the
course, and reads weeks 13 and 14 to see who came back.

What is in data. members.csv is one row per member, the way a gym's CRM would hold it, with the
goal they gave when they joined and any notes from the desk. checkins.csv is one row per door
swipe, the way a door system exports it. email_log.csv is what happened when the week 13 notes
went out, opened or not, replied or not, and the reply text, so the agent has something to stop
on.

What is in eval. answer_key_all.csv has every member with the planted pattern, whether the agent
should flag them at run 1, the reason, and whether they came back in weeks 13 and 14. It is for
the teacher. fifty_cases.csv is the fifty marked members the students score their agent against on
Thursday. It is handed out on Thursday and not before.

What is in messaging. The gym, the owner and the positioning in one page. The voice the emails are
written in and the rules the agent follows, with a bad example and a good one. And what the note
says for each kind of goal. Students get these files rather than writing them, because the
positioning work would take the week; Paul talks about why they matter.

The planted patterns, and what a fair rule finds. A rule that compares each member to their own
usual rate over weeks 1 to 9, and reads the notes, matches the answer key on all 900. The same
rule without the notes gets 38 wrong, all of them people who were away or injured. That gap is
the Monday morning lesson.

The numbers as of 5 September. 900 members, 65 flagged at run 1, 28 of those back in weeks 13 to
14. Rerun build_gym.py and they hold.`;
