#!/usr/bin/env python3
"""
Turn the course's persona copy files into a generated TS module.

⭐ WHY THIS EXISTS. The CFO persona is ~1000 words of Paul's verbatim copy and it is the
thing a student actually copies off the page. Pasting it by hand into moduleData.ts would
put his canonical copy in two places and guarantee they drift, and hand-typing a payload
this size is exactly how a word gets quietly changed. Same discipline as
extract-figures.py: one source, a regeneration path, and a generated file nobody edits.

SOURCE  ~/paul-hub/intelligence/course-build/copy/*.md
OUTPUT  src/app/course/personas.generated.ts

Run after any edit to a persona file:

    python3 scripts/extract-personas.py

⛔ Never edit the generated file. Edit the copy file and re-run.
"""

import pathlib
import re
import sys

COPY_DIR = pathlib.Path.home() / "paul-hub/intelligence/course-build/copy"
OUT = pathlib.Path(__file__).resolve().parent.parent / "src/app/course/personas.generated.ts"

# Only files that are actually reviewer personas. kite-*.md in the same folder are
# unrelated campaign copy and must not be swept in.
WANTED = ["cfo-persona.md"]


def strip_frontmatter(text: str) -> str:
    """Drop a leading --- ... --- block. It is build metadata, never student-facing."""
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            return text[end + 4 :].lstrip("\n")
    return text


# ⛔ and ⭐ are how every doc in this project marks a note written FOR THE BUILD. A persona
# file is not purely student-facing copy: cfo-persona.md carries a "## Your voice" section
# that is entirely a note to whoever builds the course, explaining why the worked example
# is absent. On 2 Aug 2026 that section rendered straight into the copy block on
# /course/1, so a student pasting the persona into Claude would have handed it a sentence
# about a session record. Build notes must never survive this script.
BUILD_MARKERS = ("⛔", "⭐", "⚠️", "PLACEHOLDER", "PAUL TO WRITE")


def strip_build_notes(text: str, label: str) -> str:
    """
    Drop any `## ` section whose body carries a build marker, and SAY SO. Never silent:
    a quietly shortened persona looks exactly like a correct one, and the only signal
    would be a student getting a worse answer months from now.
    """
    parts = re.split(r"(?m)^(?=## )", text)
    kept, dropped = [], []
    for part in parts:
        if any(m in part for m in BUILD_MARKERS):
            heading = part.splitlines()[0].strip() if part.strip() else "(unheaded)"
            dropped.append(heading)
            continue
        kept.append(part)

    for heading in dropped:
        print(f"  {label}: DROPPED build-note section {heading!r}", file=sys.stderr)

    out = "".join(kept).strip()
    # A marker outside any `## ` section cannot be dropped safely, so refuse instead of
    # guessing. Better a failed build than a note shipped to a student.
    leftover = [m for m in BUILD_MARKERS if m in out]
    if leftover:
        print(
            f"  {label}: build marker {leftover!r} outside a section. Fix the copy file.",
            file=sys.stderr,
        )
        raise SystemExit(1)
    return out


def main() -> int:
    if not COPY_DIR.is_dir():
        print(f"copy dir not found: {COPY_DIR}", file=sys.stderr)
        return 1

    out = {}
    for name in WANTED:
        src = COPY_DIR / name
        if not src.is_file():
            print(f"missing persona file: {src}", file=sys.stderr)
            return 1
        body = strip_frontmatter(src.read_text(encoding="utf-8")).strip()
        body = strip_build_notes(body, name)
        if not body:
            print(f"persona file is empty after frontmatter: {src}", file=sys.stderr)
            return 1
        key = re.sub(r"\.md$", "", name)
        out[key] = body
        print(f"{key}: {len(body.split())} words")

    lines = [
        "/**",
        " * GENERATED BY scripts/extract-personas.py. DO NOT EDIT.",
        " *",
        " * Source: ~/paul-hub/intelligence/course-build/copy/",
        " * Every word is Paul's, verbatim. To change one, edit the copy file and re-run",
        " * the script. Editing here puts his copy in two places and they will drift.",
        " */",
        "",
        "export const PERSONAS: Record<string, string> = {",
    ]
    for key, body in out.items():
        lines.append(f"  {key!r}: {body!r},".replace("'", '"', 2))
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
